vich_uploader:
    db_driver: orm

    mappings:
        admini_image:
            uri_prefix: /images/adminis
            upload_destination: '%kernel.project_dir%/public/images/adminis'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
